replicaCount: 1

image:
  repository: prom/prometheus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 9090

namespace: monitoring

config:
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'node-exporter'
      static_configs:
        - targets: ['node-exporter.monitoring.svc.cluster.local:9100']

    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']

    - job_name: 'my-app'
      static_configs:
        - targets: ['my-app.monitoring.svc.cluster.local:8080']

grafana:
  adminUser: admin
  adminPassword: Thisis4devops